#Color Constants
BLUE = (0,0,255)
GREEN = (0,255,0)
YELLOW = (255,255,0)
ORANGE = (255,127,0)
RED = (255,0,0)
PURPLE = (128,0,128)

COLORS = [ORANGE, RED, PURPLE, BLUE, GREEN, YELLOW]

#Animation Constants
ANIMATION_HEIGHT = 100
REFERENCE_HEIGHT = 100
ACCELERATION = .016
TRANSITION_ACCELERATION = .01
STUN_ACCELERATION = .008

#Motion Constants
AERIAL_ACCELERATION = .01
MAX_DRIFT_VELOCITY_COMPONENT = .3
RUN_ACCELERATION = .3
WALK_ACCELERATION = .1
JUMP_SPEED = -.7
HIGH_JUMP_SPEED = -1.

#Attack Constants
WEAK_ATTACK_MAX_DAMAGE = 50
MEDIUM_ATTACK_MAX_DAMAGE = 100
STRONG_ATTACK_MAX_DAMAGE = 150
WEAK_DAMAGE_GROWTH_RATE = 1
MEDIUM_DAMAGE_GROWTH_RATE = .6
STRONG_DAMAGE_GROWTH_RATE = .3
WEAK_STUN_TIMEOUT = 300
MEDIUM_STUN_TIMEOUT = 500
STRONG_STUN_TIMEOUT = 700
INVINCIBILITY_TIMEOUT = 1000

#AI Constants
APPROACH_PREDICTION_INTERVAL = 4000
APPROACH_PREDICTION_DELTA = 10
