#Animation Constangs
ANIMATION_HEIGHT = 100
REFERENCE_HEIGHT = 100
ACCELERATION = .01
TRANSITION_ACCELERATION = .01
STUN_ACCELERATION = .002

#Motion Constants
AERIAL_ACCELERATION = .01
MAX_DRIFT_VELOCITY_COMPONENT = .3
RUN_ACCELERATION = .3
WALK_ACCELERATION = .1

#Attack Constants
WEAK_ATTACK_MAX_DAMAGE = 50
MEDIUM_ATTACK_MAX_DAMAGE = 100
STRONG_ATTACK_MAX_DAMAGE = 150
WEAK_DAMAGE_GROWTH_RATE = 1
MEDIUM_DAMAGE_GROWTH_RATE = .75
STRONG_DAMAGE_GROWTH_RATE = .5
WEAK_STUN_TIMEOUT = 100
MEDIUM_STUN_TIMEOUT = 300
STRONG_STUN_TIMEOUT = 500

#AI Constants
APPROACH_PREDICTION_INTERVAL = 4000
APPROACH_PREDICTION_DELTA = 10
