#Animation Constangs
ANIMATION_HEIGHT = 100
REFERENCE_HEIGHT = 100
ACCELERATION = .00600
TRANSITION_ACCELERATION = .006
STUN_ACCELERATION = .002

#Motion Constants
AERIAL_ACCELERATION = .01
MAX_DRIFT_VELOCITY_COMPONENT = .3

#Attack Constants
WEAK_ATTACK_MAX_DAMAGE = 50
MEDIUM_ATTACK_MAX_DAMAGE = 100
STRONG_ATTACK_MAX_DAMAGE = 150
WEAK_DAMAGE_GROWTH_RATE = 1
MEDIUM_DAMAGE_GROWTH_RATE = .75
STRONG_DAMAGE_GROWTH_RATE = .5
